### ISSUE TITLE
cmake newbie problems

### ISSUE THREAD

**Issue by jlwoodr** [zcobell/QADCModules#35]
Hey Zach,

I have been trying to compile adcircModules for use in python using cmake in Visual Studio 2022 on my desktop and I keep running into errors. I was wondering what your preferred method is to compile this code. Do you use the cmake desktop app directly or go through VS? Thanks for your help!

Johnathan

**Comment by zcobell** [comment]
I'm not sure it will be windows compatible without some digging. I don't use it in windows except for within Windows Subsystem for Linux. For a newbie, my recommendation would be to use the provided docker container. I'm in the process of getting a Spack build configured as well, however, that too is for Linux.

**Comment by jlwoodr** [comment]
Okay, so I got docker to work, but what do I do after I enter the run command? Am I able to get the python library from this? Sorry if these are silly questions. Below is a screen shot of what I am working with. Thanks!
![image](https://user-images.githubusercontent.com/50885561/169584552-69ff7831-5f92-455a-995b-fdb0c664ef4f.png)

**Comment by zcobell** [comment]
Once you're in the container, you will have everything installed. You can check it out using: 
```
$ python3 
> import pyadcircmodules
```

**Comment by jlwoodr** [comment]
Awesome, thank you!

**Comment by jlwoodr** [comment]
Alright, so I am in the container. I am trying to read a mesh in, and I get the following error. Do I have to have my files in a specific location for docker to access them? 
![image](https://user-images.githubusercontent.com/50885561/169606345-b2b246b6-9b42-4f03-836d-464420d86f21.png)

**Comment by zcobell** [comment]
You need to copy the file to the container or mount the host filesystem to the container. Take a look at the `docker cp` command

**Comment by jlwoodr** [comment]
Got it at last. I am probably doing everything backwards but I at least have it reading a mesh finally! Thank you for your help!

**Comment by zcobell** [comment]
No problem
