### ISSUE TITLE
fort13 builder crashing with large landcover datasets

### ISSUE THREAD

**Issue by jlwoodr** [zcobell/QADCModules#36]
Hey Zach,

I was testing out the fort.13 creator and I was having problems with the code failing on larger datasets (16654 X 12031 pixels). I then tried it with a clipped portion of the larger dataset (3930 X 3784 pixels) and it worked fine. Any thoughts to why this would happen? Does docker have a memory limit? The code starts out fine with the larger data, but then dies at about 15%. Thanks!

![image](https://user-images.githubusercontent.com/50885561/169666606-c673f1c4-e553-4a75-97ce-d2e1523f79fe.png)

**Comment by zcobell** [comment]
Can you try doing:

Griddata_obj.setRasterInMemory(False)

This should minimize memory usage. I'm not sure if there is an explicit limit except that on your machine, but best to make it not read the whole thing into memory anyway for large datasets. For small datasets, there is a performance gain to have it in memory directly.

**Comment by jlwoodr** [comment]
Still fails at the same spot with the larger dataset. I am using the "Average" interpolation. Could that be the problem? Is there a nearest neighbor option?

**Comment by jlwoodr** [comment]
Nope, that crashes too at the same node number.

**Comment by zcobell** [comment]
Would it be possible for you to share your script and inputs to my TWI email?

**Comment by jlwoodr** [comment]
Yep, sure can. Thanks!

**Comment by jlwoodr** [comment]
Okay, so I think I am running out of memory on these datasets. I checked the task manager and I am maxing out cpu and memory on my desktop. I am going to tile them in to 4s and see if that works.

**Comment by jlwoodr** [comment]
Seems to be working fine now. Also, I am currently just looping through a list of landcover rasters. Is there a way to simply add this list to the interpolator instead of having to loop through every node for every raster?

**Comment by jlwoodr** [comment]
And actually I do not think the looping is working. It seems to be totally rewriting the fort.13 file each time and overwriting the nodal attributes in vertices covered by previous rasters.

**Comment by zcobell** [comment]
This issue seems to have been resolved. The issues were:

1. The raster used for directional wind reduction must use a meters based coordinate system
2. Using the method setInterpolationFlags forces the re-interpolation of all points. Instead, the setInterpolationFlag method can be used to select specific locations

**Comment by jlwoodr** [comment]
Awesome, I will make the appropriate changes. Thank you!

**Comment by zcobell** [comment]
Anytime. I sent some additional info to your email
