### ISSUE TITLE
surface canopy coefficient

### ISSUE THREAD

**Issue by jlwoodr** [zcobell/QADCModules#37]
Hey Zach,

Sorry to keep bring you my problems, but I was wondering what kind of input table I needed to calculate surface canopy coefficient. I tried using the standard computeValuesFromRaster with the DWind conversion table, but it seemed to make everything that had an actual landcover value == 0 in the output. Is there a format for the table I should follow? Like landcover of 10 would be 0 for the canopy coefficient? Is there any example of this conversion table? Thank you for your help!

**Comment by zcobell** [comment]
My typical process is to make a new table file with 1/0 for non-forest/forest types. At the end of the calculation I bin them to 0 or 1 based on some threshold. I think somewhere between 0.45 and 0.5 should bin to 0 but there's probably some testing to be done based on each area

**Comment by jlwoodr** [comment]
Zach,

Thank you for your response. I will start with your recommendation and modify if needed. Thank you!

**Comment by jlwoodr** [comment]
Zach,

FYI I was able to find a CCAP conversion table on the adcirc website in the f13builder files.
