### ISSUE TITLE
check_owi_err: Failed to 'read grid specifications/date in Oceanweather pressure file, domain 1' from './fort.221'

### ISSUE THREAD

**Issue by jalal-90** [zcobell/QADCModules#38]
Dear sir,

I prepared pressure and wind files (fort.221 and fort.222) for nws = 30. But I am getting the following error:
Failed to 'read grid specifications/date in Oceanweather pressure file, domain 1' from './fort.221'

lon range = 120:.25:140
lat range  = 20:.25:40

grid specifications/date in pressure and wind files:
iLat= 80iLong= 80DX= 0.25DY= 0.25SWLat= 10.25SWLon= 110.25DT= 201209210000

Any suggestions would be appreciated. I added the fort.221 and fort.222 files in the attachment.

[fort_221_222.zip](https://github.com/zcobell/ADCIRCModules/files/12734066/fort_221_222.zip)

**Comment by zcobell** [comment]
The format must match EXACTLY the OWI specification. Please see the example file here: https://github.com/adcirc/adcirc-testsuite/blob/v56/adcirc/adcirc_katrina-2d/fort.221

Also note that this question has nothing to do with this repository and the issue will be closed.
